- hosts: localhost
  tasks:
  - name: selinux permissive
    block:
      - name: install libselinux
        package:
          name: libselinux-python
      - name: selinux permissive
        selinux:
          policy: targeted
          state: permissive
  - name: install development packages
    package: name={{item}}
    with_items:
      - tmux
      - neovim
      - git
      - gcc
      - clang
      - golang
      - python3
      - python3-virtualenv
      - nodejs
      - npm
      - mosh
      - fish
  - name: install spotify
    block:
      - name: install snapd
        package:
          name: snapd
      - name: install spotify
        command: snap install spotify creates=/var/lib/snapd/snap/bin/spotify
  - import_tasks: dotfiles.yml
  - name: install yarn
    npm:
      name: yarn
      global: yes
