- hosts: localhost
  tasks:
  - name: disable selinux
    block:
      - name: install libselinux
        package:
          name: libselinux-python
      - name: disable selinux
        selinux:
          state: disabled
  - name: enable rpmfusion
    dnf:
      name: '{{ item }}'
      state: present
    with_items:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-27.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-27.noarch.rpm
  - name: install useful packages
    dnf:
      name: '{{ item }}'
      state: present
    with_items:
      - thunderbird
      - firefox
      - ffmpeg
  - name: install development packages
    dnf:
      name: '{{ item }}'
      state: present
    with_items:
      - tmux
      - neovim
      - git
      - gcc
      - clang
      - golang
      - python3
      - python3-virtualenv
      - nodejs
      - npm
      - mosh
      - fish
      - atom
      - docker
      - cmake
  - name: install spotify
    block:
      - name: install snapd
        dnf:
          name: snapd
      - name: install spotify
        command: snap install spotify creates=/var/lib/snapd/snap/bin/spotify
  - name: install yarn
    npm:
      name: yarn
      global: yes
  - import_tasks: dotfiles.yml
- import_playbook: fonts.yml
