#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# save a lot of history
HISTSIZE=130000 SAVEHIST=130000
# sync history between terminals
setopt share_history

alias vim=nvim
export EDITOR=nvim

# reverse incremental search with ctrl-r
bindkey '^R' history-incremental-search-backward

# accept suggestion with ctrl-n
bindkey '^N' autosuggest-accept

# some useful aliases
alias :q=exit
