#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# save a lot of history
HISTSIZE=130000 SAVEHIST=130000
# sync history between terminals
setopt share_history

alias vim=nvim
export EDITOR=nvim
export VISUAL="$EDITOR"

# launch fzf history search with ctrl-r
if [ -f ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
  bindkey '^R' fzf-history-widget
else
  # else fallback to reverse-incremental-search
  bindkey '^R' history-incremental-search-backwards
fi

# accept suggestion with ctrl-n
bindkey '^N' autosuggest-accept

# add ~/bin to PATH
export PATH="$HOME/bin:$PATH"

# some useful aliases
alias :q=exit

alias warmup="hg up remote/fbcode/warm"
export GOPATH="/data/users/vmagro/gopaths/gobuck:/data/users/vmagro/gopaths/godeps:/data/users/vmagro/gopaths/gofbcode"
export GOROOT="/data/users/vmagro/gopaths/goroot"
export PATH="/data/users/vmagro/fbsource/fbcode/third-party-buck/platform007/tools/go-tools/bin:$PATH"
export PATH="/data/users/vmagro/gopaths/goroot/bin:$PATH"

source /usr/facebook/ops/rc/master.zshrc
