- name: install development packages
  dnf:
    name: '{{ item }}'
    state: present
  with_items:
    - tmux
    - neovim
    - git
    - gcc
    - clang
    - golang
    - python3
    - python3-virtualenv
    - nodejs
    - npm
    - mosh
    - fish
    - atom
    - docker
    - cmake
    - mercurial
    - ripgrep
- name: install yarn
  npm:
    name: yarn
    global: yes
